<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-11-09T10:51:48 IST" name="Suite" finished-at="2021-11-09T10:52:06 IST" duration-ms="18074">
    <groups>
    </groups>
    <test started-at="2021-11-09T10:51:48 IST" name="test1" finished-at="2021-11-09T10:52:05 IST" duration-ms="17888">
      <class name="com.qa.TC001_RecruitmentSearch">
        <test-method is-config="true" signature="initilize()[pri:0, instance:com.qa.TC001_RecruitmentSearch@6f6a7463]" started-at="2021-11-09T10:51:48 IST" name="initilize" finished-at="2021-11-09T10:51:59 IST" duration-ms="11739" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initilize -->
        <test-method signature="loginValidation()[pri:0, instance:com.qa.TC001_RecruitmentSearch@6f6a7463]" started-at="2021-11-09T10:52:00 IST" name="loginValidation" finished-at="2021-11-09T10:52:05 IST" duration-ms="5265" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginValidation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.qa.TC001_RecruitmentSearch@6f6a7463]" started-at="2021-11-09T10:52:05 IST" name="tearDown" finished-at="2021-11-09T10:52:05 IST" duration-ms="630" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.qa.TC001_RecruitmentSearch -->
    </test> <!-- test1 -->
    <test started-at="2021-11-09T10:51:48 IST" name="test2" finished-at="2021-11-09T10:52:06 IST" duration-ms="18074">
      <class name="com.qa.TC002_RecruitmentSearch_Duplicate">
        <test-method is-config="true" signature="initilize()[pri:0, instance:com.qa.TC002_RecruitmentSearch_Duplicate@63a5e46c]" started-at="2021-11-09T10:51:48 IST" name="initilize" finished-at="2021-11-09T10:51:59 IST" duration-ms="11820" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initilize -->
        <test-method signature="loginValidation()[pri:0, instance:com.qa.TC002_RecruitmentSearch_Duplicate@63a5e46c]" started-at="2021-11-09T10:52:00 IST" name="loginValidation" finished-at="2021-11-09T10:52:05 IST" duration-ms="5051" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertFalse(Assert.java:67)
at org.testng.Assert.assertFalse(Assert.java:77)
at com.qa.TC002_RecruitmentSearch_Duplicate.loginValidation(TC002_RecruitmentSearch_Duplicate.java:42)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginValidation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.qa.TC002_RecruitmentSearch_Duplicate@63a5e46c]" started-at="2021-11-09T10:52:05 IST" name="tearDown" finished-at="2021-11-09T10:52:06 IST" duration-ms="983" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.qa.TC002_RecruitmentSearch_Duplicate -->
    </test> <!-- test2 -->
  </suite> <!-- Suite -->
</testng-results>
